#!/usr/bin/env bash
#Setting document root

if [ ! -d "/var/www/$DOCUMENT_ROOT" ]; then
  echo "Creating document root folder /var/www/$DOCUMENT_ROOT"
  mkdir -p "/var/www/$DOCUMENT_ROOT"
else
  echo "Document root folder already exists, doing nothing."
fi

echo "Setting document root to /var/www/$DOCUMENT_ROOT"
cp /etc/nginx/sites-enabled/site.conf /tmp
sed -i -e 's,root /var/www/html,root /var/www/'"$DOCUMENT_ROOT"',g' /tmp/site.conf
cat /tmp/site.conf > /etc/nginx/sites-enabled/site.conf
