FROM chayakornlpru/lprutrsys_php
MAINTAINER whitecat.chayakorn@gmail.com
ENV DEBIAN_FRONTEN noninteractive
VOLUME E:/DevelopEnvironment/trsys-src
#COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080 8443
CMD ["nginx", "-g", "daemon off;"]
